server:
  port: 9999
spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
  prefix: /imooc
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      stripPrefix: false
    search:
      path: /ad-search/**
      serviceId: eureka-client-ad-search
      stripPrefix: false